const QUOTES = 
[
    "Eat breakfast like a king, lunch like a prince, and dinner like a pauper. \n – Adelle Davis",
 "Healthy does NOT mean starving yourself EVER. Healthy means eating the right food in the right amount. \n – Karen Salmansohn",
 "It is health that is real wealth and not pieces of gold and silver. \n – Mahatma Gandhi",
 "If you keep good food in your fridge, you will eat good food. \n – Errick McAdams",
 "After dinner rest a while; after supper walk a mile. \n – T. Cogan",
 "Eating healthy food fills your body with energy and nutrients. Imagine your cells smiling back at you and saying: Thank you!. \n – Karen Salmansohn",
 "When diet is wrong, medicine is of no use. When diet is correct, medicine is of no need. \n – Ayurvedic Proverb",
 "Love yourself enough to live a healthy lifestyle. \n – Jules Robson",
 "The food you eat can be either the safest and most powerful form of medicine or the slowest form of poison. \n – Ann Wigmore",
"Sorry, there´s no magic bullet. You gotta eat healthy and live healthy to be healthy and look healthy. End of story. \n ― Morgan Spurlock",
"The only way to keep your health is to eat what you don’t want, drink what you don’t like, and do what you’d rather not. \n – Mark Twain",
"To keep the body in good health is a duty, otherwise we shall not be able to keep our mind strong and clear. \n ― Buddha",
"A fit body, a calm mind, a house full of love. These things cannot be bought \n – they must be earned. \n – Naval Ravikant",
"It is exercise alone that supports the spirits and keeps the mind in vigor. \n – Marcus Tullius Cicero",
"Your diet is a bank account. Good food choices are good investments. \n – Bethenny Frankel",
"Those who think they have no time for healthy eating will sooner or later have to find time for illness. \n – Edward Stanley",
"Don’t allow a love problem or work problem to become an eating problem. Stop trying to stuff your feelings down with food. \n – Karen Salmansohn",
"An apple a day keeps the doctor away \n – Proverb",
"In my food world, there is no fear or guilt, only joy and balance. So no ingredient is ever off-limits. Rather, all of the recipes here follow my Usually-Sometimes-Rarely philosophy. Notice there is no Never. \n ― Ellie Krieger",
"Healthy eating is a way of life, so it’s important to establish routines that are simple, realistically, and ultimately livable. \n – Horace",
"Eating crappy food isn’t a reward — it’s a punishment. \n ― Drew Carey",
"From the bitterness of disease man learns the sweetness of health. \n –Catalan Proverb",
"The human body is the best picture of the human soul. \n – Tony Robbins",
"Moderation. Small helpings. Sample a little bit of everything. These are the secrets of happiness and good health. \n – Julia Child",
"Any food that requires enhancing by the use of chemical substances should in no way be considered a food. \n – John H. Tobe",
"Healthy citizens are the greatest asset any country can have. \n ― Winston Churchill",
"Take care of yourself, be healthy, and always believe you can be successful in anything you truly want. \n – Alessandra Ambrosio",
"Health requires healthy food. \n – Roger Williams",
"Nobody can be in good health if he does not have all the time fresh air, sunshine and good water. \n – Flying Hawk",
"The more you eat, the less flavor; the less you eat, the more flavor. \n –Chinese Proverb",
"Keep healthy veggies at home, so you’ll snack on healthy veggies. \n – Karen Salmansohn",
"Sufficient sleep, exercise, healthy food, friendship, and peace of mind are necessities, not luxuries. \n – Mark Halperin",
"The scientific truth may be put quite briefly; eat moderately, having an ordinary mixed diet, and don’t worry. \n – Robert Hutchison",
"Health is like money, we never have a true idea of its value until we lose it. \n – Josh Billings",
"Let food be thy medicine, thy medicine shall be thy food. \n –Hippocrates",
"The doctor of the future will no longer treat the human frame with drugs, but rather will cure and prevent disease with nutrition. \n – Thomas Edison",
"It’s not enough to eat veggies and do yoga. You also must work on healing the stress and anger in your life. \n – Karen Salmansohn",
"Life expectancy would grow by leaps and bounds if green vegetables smelled as good as bacon. \n –Doug Larson",
"What you eat literally becomes you. you have a choice in what you’re made of. Anonymous",
"To insure good health: eat lightly, breathe deeply, live moderately, cultivate cheerfulness, and maintain an interest in life. \n –William Londen",
"Appreci-eat your food! Savor the flavor and eat slowly. It takes your body about 20 minutes to realize it’s full. \n –Karen Salmansohn",
"Your health is what you make of it. Everything you do and think either adds to the vitality, energy, and spirit you possess or takes away from it. \n – Ann Wigmore",
"Take care of your body. It’s the only place you have to live. \n – Jim Rohn",
"If you don’t take time to take care of your health now, you’re gonna have to make time for feeling sick and tired later. \n – Karen Salmansohn",
"Physical fitness is not only one of the most important keys to a healthy body, it is the basis of dynamic and creative intellectual activity. \n – John F. Kennedy",
"Doctors won’t make you healthy. Nutritionists won’t make you slim. Teachers won’t make you smart. Gurus won’t make you calm. Mentors won’t make you rich. Trainers won’t make you fit. Ultimately, you have to take responsibility. Save yourself. \n – Naval Ravikant",
"Health is a relationship between you and your body \n – Terri Guillemets",
"Water, air and cleanliness are the chief articles in my pharmacopoeia.  \n – Napoleon",
"By cleansing your body on a regular basis and eliminating as many toxins as possible from your environment, your body can begin to heal itself, prevent disease, and become stronger and more resilient than you ever dreamed possible!  \n – Dr. Edward",
"Time And health are two precious assets that we don’t recognize and appreciate until they have been depleted.  \n – Denis Waitley",
"Let thy food be thy medicine and thy medicine be thy food. \n – Hippocrates",
"To avoid sickness eat less; to prolong life worry less. \n – Chu Hui Weng",
"Don’t eat anything your great-grandmother wouldn’t recognize as food. \n – Michael Pollan",
"Cooking is at once child’s play and adult joy. And cooking done with care is an act of love. \n – Craig Claiborne",
"You are what you eat. \n – Michael Pollan",
"The primary reason diseases tend to run in families may be that diets tend to run in families. \n – Michael Greger",
"Eat food. Not too much. Mostly plants. \n – Michael Pollan",
"Focus on health, energy, vitality \n – not weight. \n – Karen Salmansohn",
"One should eat to live, not live to eat \n – Benjamin Franklin",
"Some people are willing to pay the price and it’s the same with staying healthy or eating healthy. There’s some discipline involved. There’s some sacrifices. \n – Mike Ditka",
"Processed foods not only extend the shelf life, but they extend the waistline as well. \n – Karen Sessions",
"If it came from a plant, eat it; if it was made in a plant, don’t. \n – Michael Pollan",
"About eighty percent of the food on shelves of supermarkets today didn’t exist 100 years ago.― Larry McCleary",
"By choosing healthy over skinny, you are choosing self-love over self-judgement. \n – Steve Maraboli",
"Your body is a temple, but only if you treat it as one.\n ― Astrid Alauda",
"A healthy diet is a solution to many of our health-care problems. It’s the most important solution. \n – John Mackey",
"Tell me what you eat, and I will tell you who you are. \n – Brillat-Savarin",
"Nothing has benefited me more physically, mentally and most important spiritually, then adapting a vegan diet. The best decision I have made as a human for me and the planet. \n – Tim Shieff, Professional Freerunner",
"Let things taste of what they are.― Alice Waters",
"Keeping your body healthy is an expression of gratitude to the whole cosmos \n – the trees, the clouds, everything. \n – Thich Nhat Hanh",
"Every girl and dude should be eating healthy food. \n – Unknown",
"He who takes medicine and neglects to diet wastes the skill of his doctors. \n – Chinese Proverb",
"Cake and pie may taste like heaven, but you’ll regret them when you turn 37! \n – Unknown",
"Every time you eat is an opportunity to nourish your body. \n – Unknown",
"Full of energy you will feel, after eating a healthy meal. \n – Unknown",
"Nutrition is the only remedy that can bring full recovery and can be used with any treatment. Remember, food is our best medicine! \n – Bernard Jensen",
"Even in this high-tech age, the low-tech plant continues to be the key to nutrition and health. \n – Jack Weatherford",
"Our bodies are our gardens \n – our wills are our gardeners. \n – William Shakespeare",
"To eat is a necessity, but to eat intelligently is an art. \n – La Rochefoucald",
"By choosing healthy over skinny you are choosing self-love over self-judgement. \n – Steve Maraboli",
"Healthy cooking is the best preventive medicine. \n – Unknown",
"Tell me what you eat, and I will tell you what you are. \n – Jean Anthelme Brillat-Savarin",
"I choose healthy foods for me, to stay as healthy as can be. \n – Unknown",
"There is nothing unhealthy about educating youngsters about nutrition. \n – Pierre Dukan",
"Eat healthy day and night, to keep your future looking bright. \n – Unknown",
"Eating a high-nutrient diet actually makes you more satisfied with less food, and actually gives the ability to enjoy food more without overeating. \n – Joel Fuhrman",
"A healthy outside starts from the inside. \n – Robert Urich",
"Today, more than 95% of all chronic disease is caused by food choice, toxic food ingredients, nutritional deficiencies and lack of physical exercise. \n – Mike Adams",
"Investing in early childhood nutrition is a surefire strategy. The returns are incredibly high. \n – Anne M. Mulcahy",
"When walking, walk. When eating, eat. \n – Rashaski · Zen Proverb",
"One cannot think well, love well, sleep well, if one has not dined well. \n – Virginia Woolf",
"If only you start eating healthy food, you will be pleasantly surprised how easy it is to lose weight. \n – Subodh Gupta",
"If you maintain a healthy diet, or at least are smart about your food choices, you’ll still see the pounds come off. \n – Misty May-Treanor",
"The second day of a diet is always easier than the first. By the second day you’re off it. \n – Jackie Gleason",
"Healthy people eating healthy food should never need to take an antibiotic. \n – Joel Fuhrman",
"The wise man should consider that health is the greatest of human blessings. Let food be your medicine. \n – Hippocrates",
"My passion is about motivating as many families as possible to learn about vegetables and healthy eating together. \n – Jennie Garth",
"Just like keeping a healthy diet is important to maintaining a healthy lifestyle, eating the right foods is just as important for getting the most out of your workout. \n – Marcus Samuelsson",
"The easiest diet is, you know, eat vegetables, eat fresh food. Just a really sensible healthy diet like you read about all the time. \n – Drew Carey",
"You need a good, healthy diet \n – it’s about finding out what your body needs. Sugar is a disaster for skin, as is white flour. \n – Thandie Newton"
]

const QUOTE_OF_THE_DAY = "Quote of the day : ";


export {QUOTE_OF_THE_DAY, QUOTES};
